// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXddnOUTlvLm-50XwygHMi1cxlMVTNgy8',
    appId: '1:1013131393627:web:7527ee1af8b2e56580dd7e',
    messagingSenderId: '1013131393627',
    projectId: 'hilcoe-go',
    authDomain: 'hilcoe-go.firebaseapp.com',
    storageBucket: 'hilcoe-go.firebasestorage.app',
    measurementId: 'G-7CCK9L9PYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhwVW8YdCRzsJZwUNkST8oUUep8rinnE',
    appId: '1:1013131393627:android:22de19f0f410098e80dd7e',
    messagingSenderId: '1013131393627',
    projectId: 'hilcoe-go',
    storageBucket: 'hilcoe-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybghO5CTiU08de-ngapH2fucfSCAZA5o',
    appId: '1:1013131393627:ios:1ed7f8949056caea80dd7e',
    messagingSenderId: '1013131393627',
    projectId: 'hilcoe-go',
    storageBucket: 'hilcoe-go.firebasestorage.app',
    iosBundleId: 'et.edu.hilcoe.hilcoeGo',
  );
}
